.TH "_context_awarei_phone_dev_guide" 3 "Wed Jul 16 2014" "Version ${project.version}" "context-aware-doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_context_awarei_phone_dev_guide \- ContextAware iPhone Developer Guide 
.SH "Purpose"
.PP
Purpose of this guide is to help the iPhone developers to extend their applications with the ContextAware features\&.
.SH "Prerequisites"
.PP
You need the following libraries:
.IP "1." 4
Motwin SDK version 2\&.1\&.0 or higher
.IP "2." 4
ContextAware version 1\&.0\&.0
.PP
.PP
\fBRefer to the following tutorials to integrate contextAware into your application:\fP 
.PD 0

.IP "\(bu" 2
\fBGetting Started\fP 
.IP "\(bu" 2
\fBHow to use contextElement\fP 
.IP "\(bu" 2
\fBHow to add Custom contextElement collector\fP 
.IP "\(bu" 2
\fBHow to use Tagging Api\fP 
.PP

